version: 0.2
phases:
  install:
    commands:
      - yum install -y python36-devel
      - pip3 install --upgrade sneks
      - install_dependencies
#      - pip3 install --upgrade pip awscli
#      - bash /root/scripts/install_dependencies.sh
  pre_build:
    commands:
      - setup_build_dir
#      - bash /root/scripts/setup_build_dir.sh
  build:
    commands:
      - bundle_lambda
#      - bash /root/scripts/bundle_lambda.sh
artifacts:
  files:
    - NewSamTemplate.json
  discard-paths: yes
